"""cambia la columna name a algo mas especifico

Revision ID: 5c2826d1fc11
Revises: 
Create Date: 2024-03-06 13:32:26.167113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2826d1fc11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_item', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['name_item'])
        batch_op.drop_column('name')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_store', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['name_store'])
        batch_op.drop_column('name')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_tag', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['name_tag'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name_tag')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name_store')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name_item')

    # ### end Alembic commands ###
